local _local_1_ = require("oxocharcoal.colorutils")
local blend_hex = _local_1_["blend-hex"]
if vim.g.colors_name then
  vim.cmd.hi("clear")
else
end
vim.g["colors_name"] = "oxocharcoal"
vim.o["termguicolors"] = true
vim.o["vim.g.background"] = true
local black = "#161616"
local white = "#ffffff"
local base09 = "#78a9ff"
local oxocharcoal = {black = black, grey01 = blend_hex(black, white, 0.085), grey02 = blend_hex(black, white, 0.18), grey03 = blend_hex(black, white, 0.3), grey04 = blend_hex(black, white, 0.82), grey05 = blend_hex(black, white, 0.95), white = white, cyan = "#08bdba", teal = "#3ddbd9", base09 = base09, fushia = "#ee5396", blue = "#33b1ff", pink = "#ff7eb6", green = "#42be65", lavander = "#be95ff", lightblue = "#82cfff", orange = "#ffc37e", blend = "#131313", none = "NONE"}
vim.g["terminal_color_0"] = oxocharcoal.grey01
vim.g["terminal_color_1"] = oxocharcoal.blue
vim.g["terminal_color_2"] = oxocharcoal.lavander
vim.g["terminal_color_3"] = oxocharcoal.green
vim.g["terminal_color_4"] = oxocharcoal.base09
vim.g["terminal_color_5"] = oxocharcoal.lightblue
vim.g["terminal_color_6"] = oxocharcoal.teal
vim.g["terminal_color_7"] = oxocharcoal.grey05
vim.g["terminal_color_8"] = oxocharcoal.grey03
vim.g["terminal_color_9"] = oxocharcoal.blue
vim.g["terminal_color_10"] = oxocharcoal.lavander
vim.g["terminal_color_11"] = oxocharcoal.green
vim.g["terminal_color_12"] = oxocharcoal.base09
vim.g["terminal_color_13"] = oxocharcoal.lightblue
vim.g["terminal_color_14"] = oxocharcoal.cyan
vim.g["terminal_color_15"] = oxocharcoal.white
vim.api.nvim_set_hl(0, "ColorColumn", {fg = oxocharcoal.none, bg = oxocharcoal.grey01})
vim.api.nvim_set_hl(0, "Cursor", {fg = oxocharcoal.black, bg = oxocharcoal.grey04})
vim.api.nvim_set_hl(0, "CursorLine", {fg = oxocharcoal.none, bg = oxocharcoal.grey01})
vim.api.nvim_set_hl(0, "CursorColumn", {fg = oxocharcoal.none, bg = oxocharcoal.grey01})
vim.api.nvim_set_hl(0, "CursorLineNr", {fg = oxocharcoal.grey04, bg = oxocharcoal.none})
vim.api.nvim_set_hl(0, "QuickFixLine", {fg = oxocharcoal.none, bg = oxocharcoal.grey01})
vim.api.nvim_set_hl(0, "Error", {fg = oxocharcoal.fushia, bg = oxocharcoal.grey01})
vim.api.nvim_set_hl(0, "LineNr", {fg = oxocharcoal.grey03, bg = oxocharcoal.black})
vim.api.nvim_set_hl(0, "NonText", {fg = oxocharcoal.grey02, bg = oxocharcoal.none})
vim.api.nvim_set_hl(0, "Normal", {fg = oxocharcoal.grey04, bg = oxocharcoal.black})
vim.api.nvim_set_hl(0, "Pmenu", {fg = oxocharcoal.grey04, bg = oxocharcoal.grey01})
vim.api.nvim_set_hl(0, "PmenuSbar", {fg = oxocharcoal.grey04, bg = oxocharcoal.grey01})
vim.api.nvim_set_hl(0, "PmenuSel", {fg = oxocharcoal.teal, bg = oxocharcoal.grey02})
vim.api.nvim_set_hl(0, "PmenuThumb", {fg = oxocharcoal.teal, bg = oxocharcoal.grey02})
vim.api.nvim_set_hl(0, "SpecialKey", {fg = oxocharcoal.grey03, bg = oxocharcoal.none})
vim.api.nvim_set_hl(0, "Visual", {fg = oxocharcoal.none, bg = oxocharcoal.grey02})
vim.api.nvim_set_hl(0, "VisualNOS", {fg = oxocharcoal.none, bg = oxocharcoal.grey02})
vim.api.nvim_set_hl(0, "TooLong", {fg = oxocharcoal.none, bg = oxocharcoal.grey02})
vim.api.nvim_set_hl(0, "Debug", {fg = oxocharcoal.green, bg = oxocharcoal.none})
vim.api.nvim_set_hl(0, "Macro", {fg = oxocharcoal.cyan, bg = oxocharcoal.none})
vim.api.nvim_set_hl(0, "MatchParen", {fg = oxocharcoal.none, bg = oxocharcoal.grey02, underline = true})
vim.api.nvim_set_hl(0, "Bold", {fg = oxocharcoal.none, bg = oxocharcoal.none, bold = true})
vim.api.nvim_set_hl(0, "Italic", {fg = oxocharcoal.none, bg = oxocharcoal.none, italic = true})
vim.api.nvim_set_hl(0, "Underlined", {fg = oxocharcoal.none, bg = oxocharcoal.none, underline = true})
vim.api.nvim_set_hl(0, "DiagnosticWarn", {fg = oxocharcoal.lavander, bg = oxocharcoal.none})
vim.api.nvim_set_hl(0, "DiagnosticError", {fg = oxocharcoal.fushia, bg = oxocharcoal.none})
vim.api.nvim_set_hl(0, "DiagnosticInfo", {fg = oxocharcoal.base09, bg = oxocharcoal.none})
vim.api.nvim_set_hl(0, "DiagnosticHint", {fg = oxocharcoal.grey04, bg = oxocharcoal.none})
vim.api.nvim_set_hl(0, "DiagnosticUnderlineWarn", {fg = oxocharcoal.lavander, bg = oxocharcoal.none, undercurl = true})
vim.api.nvim_set_hl(0, "DiagnosticUnderlineError", {fg = oxocharcoal.fushia, bg = oxocharcoal.none, undercurl = true})
vim.api.nvim_set_hl(0, "DiagnosticUnderlineInfo", {fg = oxocharcoal.grey04, bg = oxocharcoal.none, undercurl = true})
vim.api.nvim_set_hl(0, "DiagnosticUnderlineHint", {fg = oxocharcoal.grey04, bg = oxocharcoal.none, undercurl = true})
vim.api.nvim_set_hl(0, "HealthError", {fg = oxocharcoal.fushia, bg = oxocharcoal.none})
vim.api.nvim_set_hl(0, "HealthWarning", {fg = oxocharcoal.lavander, bg = oxocharcoal.none})
vim.api.nvim_set_hl(0, "HealthSuccess", {fg = oxocharcoal.green, bg = oxocharcoal.none})
vim.api.nvim_set_hl(0, "@text.literal.commodity", {fg = oxocharcoal.green, bg = oxocharcoal.none})
vim.api.nvim_set_hl(0, "@number", {fg = oxocharcoal.base09, bg = oxocharcoal.none})
vim.api.nvim_set_hl(0, "@number.date", {fg = oxocharcoal.teal, bg = oxocharcoal.none})
vim.api.nvim_set_hl(0, "@number.date.effective", {fg = oxocharcoal.green, bg = oxocharcoal.none})
vim.api.nvim_set_hl(0, "@number.interval", {fg = oxocharcoal.base09, bg = oxocharcoal.none})
vim.api.nvim_set_hl(0, "@number.status", {fg = oxocharcoal.pink, bg = oxocharcoal.none})
vim.api.nvim_set_hl(0, "@number.quantity", {fg = oxocharcoal.blue, bg = oxocharcoal.none})
vim.api.nvim_set_hl(0, "@number.quantity.negative", {fg = oxocharcoal.fushia, bg = oxocharcoal.none})
vim.api.nvim_set_hl(0, "LspReferenceText", {fg = oxocharcoal.none, bg = oxocharcoal.grey03})
vim.api.nvim_set_hl(0, "LspReferenceread", {fg = oxocharcoal.none, bg = oxocharcoal.grey03})
vim.api.nvim_set_hl(0, "LspReferenceWrite", {fg = oxocharcoal.none, bg = oxocharcoal.grey03})
vim.api.nvim_set_hl(0, "LspSignatureActiveParameter", {fg = oxocharcoal.teal, bg = oxocharcoal.none, bold = true})
vim.api.nvim_set_hl(0, "keyword", {fg = "#94C4FF", bg = oxocharcoal.none})
vim.api.nvim_set_hl(0, "identifier", {fg = "#E9B1FF", bg = oxocharcoal.none})
vim.api.nvim_set_hl(0, "string", {fg = "#96BE78", bg = oxocharcoal.none})
vim.api.nvim_set_hl(0, "escape_char", {fg = "#50B4BE", bg = oxocharcoal.none})
vim.api.nvim_set_hl(0, "constant", {fg = "#96BE78", bg = oxocharcoal.none})
vim.api.nvim_set_hl(0, "comment", {fg = "#808080", bg = oxocharcoal.none})
vim.api.nvim_set_hl(0, "todo", {fg = "#C8B47D", bg = oxocharcoal.none})
vim.api.nvim_set_hl(0, "note", {fg = "#61AFE1", bg = oxocharcoal.none})
vim.api.nvim_set_hl(0, "warn", {fg = "#E88C00", bg = oxocharcoal.none})
vim.api.nvim_set_hl(0, "error", {fg = "#DD3962", bg = oxocharcoal.none})
vim.api.nvim_set_hl(0, "preprocessor", {fg = "#C88CDC", bg = oxocharcoal.none})
vim.api.nvim_set_hl(0, "number", {fg = "#96BE78", bg = oxocharcoal.none})
vim.api.nvim_set_hl(0, "label", {fg = "#B7B7B7", bg = oxocharcoal.none})
vim.api.nvim_set_hl(0, "operator", {fg = "#BED4E0", bg = oxocharcoal.none})
vim.api.nvim_set_hl(0, "type", {fg = "#E9B1FF", bg = oxocharcoal.none})
vim.api.nvim_set_hl(0, "method", {fg = "#FFB987", bg = oxocharcoal.none})
vim.api.nvim_set_hl(0, "punctuation", {fg = "#BED4E0", bg = oxocharcoal.none})
vim.api.nvim_set_hl(0, "instance_field", {fg = "#FF9696", bg = oxocharcoal.none})
vim.api.nvim_set_hl(0, "decorator", {fg = "#BBB529", bg = oxocharcoal.none})
vim.api.nvim_set_hl(0, "self_param", {fg = "#94C4FF", bg = oxocharcoal.none})
vim.api.nvim_set_hl(0, "format_item", {fg = "#80FF80", bg = oxocharcoal.none})
vim.api.nvim_set_hl(0, "interface", {fg = "#FFCF97", bg = oxocharcoal.none})
vim.api.nvim_set_hl(0, "namespace", {fg = "#E9B1FF", bg = oxocharcoal.none})
vim.api.nvim_set_hl(0, "parameter", {fg = "#97F1FD", bg = oxocharcoal.none})
vim.api.nvim_set_hl(0, "variable", {fg = "#FFFFFF", bg = oxocharcoal.none})
vim.api.nvim_set_hl(0, "symbol", {fg = "#E9B1FF", bg = oxocharcoal.none})
vim.api.nvim_set_hl(0, "lifetime", {fg = "#50B4BE", bg = oxocharcoal.none})
vim.api.nvim_set_hl(0, "text", {fg = "#DADFE5", bg = oxocharcoal.none})
vim.api.nvim_set_hl(0, "text_heading", {fg = "#C88CDC", bg = oxocharcoal.none})
vim.api.nvim_set_hl(0, "uri", {fg = "#61AFE1", bg = oxocharcoal.none})
vim.api.nvim_set_hl(0, "@lsp.type.class", {link = "type"})
vim.api.nvim_set_hl(0, "@lsp.type.decorator", {link = "decorator"})
vim.api.nvim_set_hl(0, "@lsp.type.function", {link = "method"})
vim.api.nvim_set_hl(0, "@lsp.type.macro", {})
vim.api.nvim_set_hl(0, "@lsp.type.method", {link = "method"})
vim.api.nvim_set_hl(0, "@lsp.type.struct", {link = "type"})
vim.api.nvim_set_hl(0, "@lsp.type.type", {link = "type"})
vim.api.nvim_set_hl(0, "@lsp.type.typeParameter", {link = "keyword"})
vim.api.nvim_set_hl(0, "@lsp.type.selfParameter", {link = "self_param"})
vim.api.nvim_set_hl(0, "@lsp.type.builtinConstant", {link = "constant"})
vim.api.nvim_set_hl(0, "@lsp.type.magicFunction", {link = "method"})
vim.api.nvim_set_hl(0, "@lsp.type.boolean", {link = "keyword"})
vim.api.nvim_set_hl(0, "@lsp.type.builtinType", {link = "type"})
vim.api.nvim_set_hl(0, "@lsp.type.comment", {link = "comment"})
vim.api.nvim_set_hl(0, "@lsp.type.enum", {link = "type"})
vim.api.nvim_set_hl(0, "@lsp.type.enumMember", {link = "constant"})
vim.api.nvim_set_hl(0, "@lsp.type.escapeSequence", {link = "escape_char"})
vim.api.nvim_set_hl(0, "@lsp.type.formatSpecifier", {link = "format_item"})
vim.api.nvim_set_hl(0, "@lsp.type.interface", {link = "interface"})
vim.api.nvim_set_hl(0, "@lsp.type.keyword", {link = "keyword"})
vim.api.nvim_set_hl(0, "@lsp.type.namespace", {link = "namespace"})
vim.api.nvim_set_hl(0, "@lsp.type.number", {link = "number"})
vim.api.nvim_set_hl(0, "@lsp.type.operator", {link = "operator"})
vim.api.nvim_set_hl(0, "@lsp.type.parameter", {link = "parameter"})
vim.api.nvim_set_hl(0, "@lsp.type.property", {link = "instance_field"})
vim.api.nvim_set_hl(0, "@lsp.type.selfKeyword", {link = "self_param"})
vim.api.nvim_set_hl(0, "@lsp.type.string.rust", {link = "string"})
vim.api.nvim_set_hl(0, "@lsp.type.typeAlias", {link = "type"})
vim.api.nvim_set_hl(0, "@lsp.type.unresolvedReference", {link = "error"})
vim.api.nvim_set_hl(0, "@lsp.type.variable", {link = "variable"})
vim.api.nvim_set_hl(0, "@lsp.typemod.variable.globalScope", {link = "identifier"})
vim.api.nvim_set_hl(0, "@lsp.mod.readonly", {})
vim.api.nvim_set_hl(0, "@lsp.mod.typeHint", {link = "type"})
vim.api.nvim_set_hl(0, "@lsp.mod.builtin", {})
vim.api.nvim_set_hl(0, "@lsp.typemod.class.defaultLibrary", {link = "type"})
vim.api.nvim_set_hl(0, "@lsp.typemod.enum.defaultLibrary", {link = "type"})
vim.api.nvim_set_hl(0, "@lsp.typemod.enumMember.defaultLibrary", {link = "constant"})
vim.api.nvim_set_hl(0, "@lsp.typemod.function.defaultLibrary", {link = "method"})
vim.api.nvim_set_hl(0, "@lsp.typemod.keyword.async", {link = "keyword"})
vim.api.nvim_set_hl(0, "@lsp.typemod.macro.defaultLibrary", {})
vim.api.nvim_set_hl(0, "@lsp.typemod.method.defaultLibrary", {})
vim.api.nvim_set_hl(0, "@lsp.typemod.operator.injected", {link = "operator"})
vim.api.nvim_set_hl(0, "@lsp.typemod.string.injected", {link = "string"})
vim.api.nvim_set_hl(0, "@lsp.typemod.operator.controlFlow", {})
vim.api.nvim_set_hl(0, "@lsp.typemod.keyword.documentation", {})
vim.api.nvim_set_hl(0, "@lsp.typemod.variable.global", {link = "symbol"})
vim.api.nvim_set_hl(0, "@lsp.typemod.variable.static", {})
vim.api.nvim_set_hl(0, "@lsp.typemod.variable.defaultLibrary", {})
vim.api.nvim_set_hl(0, "@lsp.typemod.function.builtin", {})
vim.api.nvim_set_hl(0, "@lsp.typemod.function.readonly", {})
vim.api.nvim_set_hl(0, "@lsp.typemod.type.defaultLibrary", {})
vim.api.nvim_set_hl(0, "@lsp.typemod.variable.defaultLibrary", {})
vim.api.nvim_set_hl(0, "@lsp.typemod.variable.injected", {link = "variable"})
vim.api.nvim_set_hl(0, "@comment", {link = "comment"})
vim.api.nvim_set_hl(0, "@comment.todo", {link = "todo"})
vim.api.nvim_set_hl(0, "@comment.note", {link = "note"})
vim.api.nvim_set_hl(0, "@comment.warning", {link = "warn"})
vim.api.nvim_set_hl(0, "@comment.error", {link = "error"})
vim.api.nvim_set_hl(0, "@error", {link = "error"})
vim.api.nvim_set_hl(0, "@preproc", {link = "preprocessor"})
vim.api.nvim_set_hl(0, "@define", {link = "preprocessor"})
vim.api.nvim_set_hl(0, "@operator", {link = "operator"})
vim.api.nvim_set_hl(0, "@punctuation.delimiter", {link = "punctuation"})
vim.api.nvim_set_hl(0, "@punctuation.bracket", {link = "punctuation"})
vim.api.nvim_set_hl(0, "@punctuation.special", {link = "punctuation"})
vim.api.nvim_set_hl(0, "@string", {link = "string"})
vim.api.nvim_set_hl(0, "@string.regex", {link = "regex"})
vim.api.nvim_set_hl(0, "@string.escape", {link = "escape_char"})
vim.api.nvim_set_hl(0, "@character", {link = "string"})
vim.api.nvim_set_hl(0, "@boolean", {link = "keyword"})
vim.api.nvim_set_hl(0, "@number", {link = "number"})
vim.api.nvim_set_hl(0, "@float", {link = "number"})
vim.api.nvim_set_hl(0, "@function", {link = "method"})
vim.api.nvim_set_hl(0, "@function.builtin", {link = "method"})
vim.api.nvim_set_hl(0, "@function.macro", {link = "method"})
vim.api.nvim_set_hl(0, "@method", {link = "method"})
vim.api.nvim_set_hl(0, "@constructor", {link = "type"})
vim.api.nvim_set_hl(0, "@parameter", {link = "parameter"})
vim.api.nvim_set_hl(0, "@keyword", {link = "keyword"})
vim.api.nvim_set_hl(0, "@keyword.function", {link = "keyword"})
vim.api.nvim_set_hl(0, "@keyword.operator", {link = "operator"})
vim.api.nvim_set_hl(0, "@conditional", {link = "keyword"})
vim.api.nvim_set_hl(0, "@repeat", {link = "keyword"})
vim.api.nvim_set_hl(0, "@label", {link = "label"})
vim.api.nvim_set_hl(0, "@include", {link = "preprocessor"})
vim.api.nvim_set_hl(0, "@exception", {})
vim.api.nvim_set_hl(0, "@type", {link = "type"})
vim.api.nvim_set_hl(0, "@type.builtin", {link = "type"})
vim.api.nvim_set_hl(0, "@type.qualifier", {link = "keyword"})
vim.api.nvim_set_hl(0, "@type.storageclass", {link = "keyword"})
vim.api.nvim_set_hl(0, "@type.lifetime", {link = "lifetime"})
vim.api.nvim_set_hl(0, "@attribute", {link = "decorator"})
vim.api.nvim_set_hl(0, "@field", {link = "instance_field"})
vim.api.nvim_set_hl(0, "@property", {link = "instance_field"})
vim.api.nvim_set_hl(0, "@variable", {link = "variable"})
vim.api.nvim_set_hl(0, "@variable.builtin", {link = "variable"})
vim.api.nvim_set_hl(0, "@variable.global", {link = "identifier"})
vim.api.nvim_set_hl(0, "@constant", {link = "constant"})
vim.api.nvim_set_hl(0, "@constant.builtin", {link = "constant"})
vim.api.nvim_set_hl(0, "@constant.macro", {})
vim.api.nvim_set_hl(0, "@namespace", {link = "namespace"})
vim.api.nvim_set_hl(0, "@symbol", {link = "symbol"})
vim.api.nvim_set_hl(0, "@markup", {link = "text"})
vim.api.nvim_set_hl(0, "@markup.strong", {link = "text", bold = true})
vim.api.nvim_set_hl(0, "@markup.emphasis", {link = "text", bold = true, italic = true})
vim.api.nvim_set_hl(0, "@markup.underline", {link = "text", underline = true})
vim.api.nvim_set_hl(0, "@markup.strike", {link = "text", strikethrough = true})
vim.api.nvim_set_hl(0, "@markup.title", {link = "text_heading"})
vim.api.nvim_set_hl(0, "@markup.literal", {link = "text"})
vim.api.nvim_set_hl(0, "@markup.uri", {link = "uri", underline = true})
vim.api.nvim_set_hl(0, "@markup.todo", {link = "todo"})
vim.api.nvim_set_hl(0, "@markup.note", {link = "note"})
vim.api.nvim_set_hl(0, "@markup.warning", {link = "warn"})
vim.api.nvim_set_hl(0, "@markup.danger", {link = "error"})
vim.api.nvim_set_hl(0, "@tag", {fg = oxocharcoal.base09, bg = oxocharcoal.none})
vim.api.nvim_set_hl(0, "@tag.attribute", {fg = oxocharcoal.lightblue, bg = oxocharcoal.none})
vim.api.nvim_set_hl(0, "@tag.delimiter", {fg = oxocharcoal.lightblue, bg = oxocharcoal.none})
vim.api.nvim_set_hl(0, "@reference", {fg = oxocharcoal.grey04, bg = oxocharcoal.none})
vim.api.nvim_set_hl(0, "Folded", {fg = oxocharcoal.grey02, bg = oxocharcoal.grey01})
vim.api.nvim_set_hl(0, "FoldColumn", {fg = oxocharcoal.grey01, bg = oxocharcoal.black})
vim.api.nvim_set_hl(0, "SignColumn", {fg = oxocharcoal.grey01, bg = oxocharcoal.black})
vim.api.nvim_set_hl(0, "Directory", {fg = oxocharcoal.teal, bg = oxocharcoal.none})
vim.api.nvim_set_hl(0, "EndOfBuffer", {fg = oxocharcoal.grey01, bg = oxocharcoal.none})
vim.api.nvim_set_hl(0, "ErrorMsg", {fg = oxocharcoal.fushia, bg = oxocharcoal.none})
vim.api.nvim_set_hl(0, "ModeMsg", {fg = oxocharcoal.grey04, bg = oxocharcoal.none})
vim.api.nvim_set_hl(0, "MoreMsg", {fg = oxocharcoal.teal, bg = oxocharcoal.none})
vim.api.nvim_set_hl(0, "Question", {fg = oxocharcoal.grey04, bg = oxocharcoal.none})
vim.api.nvim_set_hl(0, "Substitute", {fg = oxocharcoal.grey01, bg = oxocharcoal.teal})
vim.api.nvim_set_hl(0, "WarningMsg", {fg = oxocharcoal.lavander, bg = oxocharcoal.none})
vim.api.nvim_set_hl(0, "WildMenu", {fg = oxocharcoal.teal, bg = oxocharcoal.grey01})
vim.api.nvim_set_hl(0, "helpHyperTextJump", {fg = oxocharcoal.teal, bg = oxocharcoal.none})
vim.api.nvim_set_hl(0, "helpSpecial", {fg = oxocharcoal.base09, bg = oxocharcoal.none})
vim.api.nvim_set_hl(0, "helpHeadline", {fg = oxocharcoal.fushia, bg = oxocharcoal.none})
vim.api.nvim_set_hl(0, "helpHeader", {fg = oxocharcoal.lightblue, bg = oxocharcoal.none})
vim.api.nvim_set_hl(0, "DiffAdded", {fg = oxocharcoal.cyan, bg = oxocharcoal.none})
vim.api.nvim_set_hl(0, "DiffChanged", {fg = oxocharcoal.base09, bg = oxocharcoal.none})
vim.api.nvim_set_hl(0, "DiffRemoved", {fg = oxocharcoal.fushia, bg = oxocharcoal.none})
vim.api.nvim_set_hl(0, "DiffAdd", {bg = "#122f2f", fg = oxocharcoal.none})
vim.api.nvim_set_hl(0, "DiffChange", {bg = "#222a39", fg = oxocharcoal.none})
vim.api.nvim_set_hl(0, "DiffText", {bg = "#2f3f5c", fg = oxocharcoal.none})
vim.api.nvim_set_hl(0, "DiffDelete", {bg = "#361c28", fg = oxocharcoal.none})
vim.api.nvim_set_hl(0, "IncSearch", {fg = oxocharcoal.white, bg = oxocharcoal.fushia})
vim.api.nvim_set_hl(0, "Search", {fg = oxocharcoal.grey01, bg = oxocharcoal.teal})
vim.api.nvim_set_hl(0, "TabLine", {link = "StatusLineNC"})
vim.api.nvim_set_hl(0, "TabLineFill", {link = "TabLine"})
vim.api.nvim_set_hl(0, "TabLineSel", {link = "StatusLine"})
vim.api.nvim_set_hl(0, "Title", {fg = oxocharcoal.grey04, bg = oxocharcoal.none})
vim.api.nvim_set_hl(0, "VertSplit", {fg = oxocharcoal.grey01, bg = oxocharcoal.black})
vim.api.nvim_set_hl(0, "markdownBlockquote", {fg = oxocharcoal.teal, bg = oxocharcoal.none})
vim.api.nvim_set_hl(0, "markdownBold", {link = "Bold"})
vim.api.nvim_set_hl(0, "markdownItalic", {link = "Italic"})
vim.api.nvim_set_hl(0, "markdownBoldItalic", {fg = oxocharcoal.none, bg = oxocharcoal.none, bold = true, italic = true})
vim.api.nvim_set_hl(0, "markdownRule", {link = "Comment"})
vim.api.nvim_set_hl(0, "markdownH1", {fg = oxocharcoal.fushia, bg = oxocharcoal.none})
vim.api.nvim_set_hl(0, "markdownH2", {link = "markdownH1"})
vim.api.nvim_set_hl(0, "markdownH3", {link = "markdownH1"})
vim.api.nvim_set_hl(0, "markdownH4", {link = "markdownH1"})
vim.api.nvim_set_hl(0, "markdownH5", {link = "markdownH1"})
vim.api.nvim_set_hl(0, "markdownH6", {link = "markdownH1"})
vim.api.nvim_set_hl(0, "markdownHeadingDelimiter", {link = "markdownH1"})
vim.api.nvim_set_hl(0, "markdownHeadingRule", {link = "markdownH1"})
vim.api.nvim_set_hl(0, "markdownUrl", {fg = oxocharcoal.lavander, bg = oxocharcoal.none, underline = true})
vim.api.nvim_set_hl(0, "markdownCode", {link = "String"})
vim.api.nvim_set_hl(0, "markdownCodeBlock", {link = "markdownCode"})
vim.api.nvim_set_hl(0, "markdownCodeDelimiter", {link = "markdownCode"})
vim.api.nvim_set_hl(0, "markdownUrl", {link = "String"})
vim.api.nvim_set_hl(0, "markdownListMarker", {fg = oxocharcoal.teal, bg = oxocharcoal.none})
vim.api.nvim_set_hl(0, "markdownOrderedListMarker", {fg = oxocharcoal.teal, bg = oxocharcoal.none})
vim.api.nvim_set_hl(0, "asciidocAttributeEntry", {fg = oxocharcoal.lightblue, bg = oxocharcoal.none})
vim.api.nvim_set_hl(0, "asciidocAttributeList", {link = "asciidocAttributeEntry"})
vim.api.nvim_set_hl(0, "asciidocAttributeRef", {link = "asciidocAttributeEntry"})
vim.api.nvim_set_hl(0, "asciidocHLabel", {link = "markdownH1"})
vim.api.nvim_set_hl(0, "asciidocOneLineTitle", {link = "markdownH1"})
vim.api.nvim_set_hl(0, "asciidocQuotedMonospaced", {link = "markdownBlockquote"})
vim.api.nvim_set_hl(0, "asciidocURL", {link = "markdownUrl"})
vim.api.nvim_set_hl(0, "NvimInternalError", {fg = oxocharcoal.black, bg = oxocharcoal.teal})
vim.api.nvim_set_hl(0, "NormalFloat", {fg = oxocharcoal.grey05, bg = oxocharcoal.blend})
vim.api.nvim_set_hl(0, "FloatBorder", {fg = oxocharcoal.blend, bg = oxocharcoal.blend})
vim.api.nvim_set_hl(0, "NormalNC", {fg = oxocharcoal.grey05, bg = oxocharcoal.black})
vim.api.nvim_set_hl(0, "TermCursor", {fg = oxocharcoal.black, bg = oxocharcoal.grey04})
vim.api.nvim_set_hl(0, "TermCursorNC", {fg = oxocharcoal.black, bg = oxocharcoal.grey04})
vim.api.nvim_set_hl(0, "StatusLine", {fg = oxocharcoal.grey04, bg = oxocharcoal.black})
vim.api.nvim_set_hl(0, "StatusLineNC", {fg = oxocharcoal.grey04, bg = oxocharcoal.grey01})
vim.api.nvim_set_hl(0, "StatusReplace", {fg = oxocharcoal.black, bg = oxocharcoal.teal})
vim.api.nvim_set_hl(0, "StatusInsert", {fg = oxocharcoal.black, bg = oxocharcoal.pink})
vim.api.nvim_set_hl(0, "StatusVisual", {fg = oxocharcoal.black, bg = oxocharcoal.lavander})
vim.api.nvim_set_hl(0, "StatusTerminal", {fg = oxocharcoal.black, bg = oxocharcoal.blue})
vim.api.nvim_set_hl(0, "StatusNormal", {fg = oxocharcoal.black, bg = oxocharcoal.lightblue})
vim.api.nvim_set_hl(0, "StatusCommand", {fg = oxocharcoal.black, bg = oxocharcoal.green})
vim.api.nvim_set_hl(0, "StatusLineDiagnosticWarn", {fg = oxocharcoal.lavander, bg = oxocharcoal.black, bold = true})
vim.api.nvim_set_hl(0, "StatusLineDiagnosticError", {fg = oxocharcoal.fushia, bg = oxocharcoal.black, bold = true})
vim.api.nvim_set_hl(0, "TelescopeBorder", {fg = oxocharcoal.blend, bg = oxocharcoal.blend})
vim.api.nvim_set_hl(0, "TelescopePromptBorder", {fg = oxocharcoal.grey02, bg = oxocharcoal.grey02})
vim.api.nvim_set_hl(0, "TelescopePromptNormal", {fg = oxocharcoal.grey05, bg = oxocharcoal.grey02})
vim.api.nvim_set_hl(0, "TelescopePromptPrefix", {fg = oxocharcoal.teal, bg = oxocharcoal.grey02})
vim.api.nvim_set_hl(0, "TelescopeNormal", {fg = oxocharcoal.none, bg = oxocharcoal.blend})
vim.api.nvim_set_hl(0, "TelescopePreviewTitle", {fg = oxocharcoal.grey02, bg = oxocharcoal.pink})
vim.api.nvim_set_hl(0, "TelescopePromptTitle", {fg = oxocharcoal.grey02, bg = oxocharcoal.blue})
vim.api.nvim_set_hl(0, "TelescopeResultsTitle", {fg = oxocharcoal.blend, bg = oxocharcoal.blend})
vim.api.nvim_set_hl(0, "TelescopeSelection", {fg = oxocharcoal.none, bg = oxocharcoal.grey02})
vim.api.nvim_set_hl(0, "TelescopePreviewLine", {fg = oxocharcoal.none, bg = oxocharcoal.grey01})
vim.api.nvim_set_hl(0, "TelescopeMatching", {fg = oxocharcoal.teal, bg = oxocharcoal.none, bold = true, italic = true})
vim.api.nvim_set_hl(0, "NotifyERRORBorder", {fg = oxocharcoal.teal, bg = oxocharcoal.none})
vim.api.nvim_set_hl(0, "NotifyWARNBorder", {fg = oxocharcoal.lavander, bg = oxocharcoal.none})
vim.api.nvim_set_hl(0, "NotifyINFOBorder", {fg = oxocharcoal.grey05, bg = oxocharcoal.none})
vim.api.nvim_set_hl(0, "NotifyDEBUGBorder", {fg = oxocharcoal.green, bg = oxocharcoal.none})
vim.api.nvim_set_hl(0, "NotifyTRACEBorder", {fg = oxocharcoal.green, bg = oxocharcoal.none})
vim.api.nvim_set_hl(0, "NotifyERRORIcon", {fg = oxocharcoal.teal, bg = oxocharcoal.none})
vim.api.nvim_set_hl(0, "NotifyWARNIcon", {fg = oxocharcoal.lavander, bg = oxocharcoal.none})
vim.api.nvim_set_hl(0, "NotifyINFOIcon", {fg = oxocharcoal.grey05, bg = oxocharcoal.none})
vim.api.nvim_set_hl(0, "NotifyDEBUGIcon", {fg = oxocharcoal.green, bg = oxocharcoal.none})
vim.api.nvim_set_hl(0, "NotifyTRACEIcon", {fg = oxocharcoal.green, bg = oxocharcoal.none})
vim.api.nvim_set_hl(0, "NotifyERRORTitle", {fg = oxocharcoal.teal, bg = oxocharcoal.none})
vim.api.nvim_set_hl(0, "NotifyWARNTitle", {fg = oxocharcoal.lavander, bg = oxocharcoal.none})
vim.api.nvim_set_hl(0, "NotifyINFOTitle", {fg = oxocharcoal.grey05, bg = oxocharcoal.none})
vim.api.nvim_set_hl(0, "NotifyDEBUGTitle", {fg = oxocharcoal.green, bg = oxocharcoal.none})
vim.api.nvim_set_hl(0, "NotifyTRACETitle", {fg = oxocharcoal.green, bg = oxocharcoal.none})
vim.api.nvim_set_hl(0, "CmpItemAbbr", {fg = "#adadad", bg = oxocharcoal.none})
vim.api.nvim_set_hl(0, "CmpItemAbbrMatch", {fg = oxocharcoal.grey05, bg = oxocharcoal.none, bold = true})
vim.api.nvim_set_hl(0, "CmpItemAbbrMatchFuzzy", {fg = oxocharcoal.grey04, bg = oxocharcoal.none, bold = true})
vim.api.nvim_set_hl(0, "CmpItemMenu", {fg = oxocharcoal.grey04, bg = oxocharcoal.none, italic = true})
vim.api.nvim_set_hl(0, "CmpItemKindInterface", {fg = oxocharcoal.grey01, bg = oxocharcoal.teal})
vim.api.nvim_set_hl(0, "CmpItemKindColor", {fg = oxocharcoal.grey01, bg = oxocharcoal.teal})
vim.api.nvim_set_hl(0, "CmpItemKindTypeParameter", {fg = oxocharcoal.grey01, bg = oxocharcoal.teal})
vim.api.nvim_set_hl(0, "CmpItemKindText", {fg = oxocharcoal.grey01, bg = oxocharcoal.base09})
vim.api.nvim_set_hl(0, "CmpItemKindEnum", {fg = oxocharcoal.grey01, bg = oxocharcoal.base09})
vim.api.nvim_set_hl(0, "CmpItemKindKeyword", {fg = oxocharcoal.grey01, bg = oxocharcoal.base09})
vim.api.nvim_set_hl(0, "CmpItemKindConstant", {fg = oxocharcoal.grey01, bg = oxocharcoal.orange})
vim.api.nvim_set_hl(0, "CmpItemKindConstructor", {fg = oxocharcoal.grey01, bg = oxocharcoal.orange})
vim.api.nvim_set_hl(0, "CmpItemKindReference", {fg = oxocharcoal.grey01, bg = oxocharcoal.orange})
vim.api.nvim_set_hl(0, "CmpItemKindFunction", {fg = oxocharcoal.grey01, bg = oxocharcoal.blue})
vim.api.nvim_set_hl(0, "CmpItemKindStruct", {fg = oxocharcoal.grey01, bg = oxocharcoal.blue})
vim.api.nvim_set_hl(0, "CmpItemKindClass", {fg = oxocharcoal.grey01, bg = oxocharcoal.blue})
vim.api.nvim_set_hl(0, "CmpItemKindModule", {fg = oxocharcoal.grey01, bg = oxocharcoal.blue})
vim.api.nvim_set_hl(0, "CmpItemKindOperator", {fg = oxocharcoal.grey01, bg = oxocharcoal.blue})
vim.api.nvim_set_hl(0, "CmpItemKindField", {fg = oxocharcoal.grey01, bg = oxocharcoal.pink})
vim.api.nvim_set_hl(0, "CmpItemKindProperty", {fg = oxocharcoal.grey01, bg = oxocharcoal.pink})
vim.api.nvim_set_hl(0, "CmpItemKindEvent", {fg = oxocharcoal.grey01, bg = oxocharcoal.pink})
vim.api.nvim_set_hl(0, "CmpItemKindUnit", {fg = oxocharcoal.grey01, bg = oxocharcoal.green})
vim.api.nvim_set_hl(0, "CmpItemKindSnippet", {fg = oxocharcoal.grey01, bg = oxocharcoal.green})
vim.api.nvim_set_hl(0, "CmpItemKindFolder", {fg = oxocharcoal.grey01, bg = oxocharcoal.green})
vim.api.nvim_set_hl(0, "CmpItemKindVariable", {fg = oxocharcoal.grey01, bg = oxocharcoal.lavander})
vim.api.nvim_set_hl(0, "CmpItemKindFile", {fg = oxocharcoal.grey01, bg = oxocharcoal.lavander})
vim.api.nvim_set_hl(0, "CmpItemKindMethod", {fg = oxocharcoal.grey01, bg = oxocharcoal.lightblue})
vim.api.nvim_set_hl(0, "CmpItemKindValue", {fg = oxocharcoal.grey01, bg = oxocharcoal.lightblue})
vim.api.nvim_set_hl(0, "CmpItemKindEnumMember", {fg = oxocharcoal.grey01, bg = oxocharcoal.lightblue})
vim.api.nvim_set_hl(0, "NvimTreeImageFile", {fg = oxocharcoal.pink, bg = oxocharcoal.none})
vim.api.nvim_set_hl(0, "NvimTreeFolderIcon", {fg = oxocharcoal.pink, bg = oxocharcoal.none})
vim.api.nvim_set_hl(0, "NvimTreeWinSeparator", {fg = oxocharcoal.black, bg = oxocharcoal.black})
vim.api.nvim_set_hl(0, "NvimTreeFolderName", {fg = oxocharcoal.base09, bg = oxocharcoal.none})
vim.api.nvim_set_hl(0, "NvimTreeIndentMarker", {fg = oxocharcoal.grey02, bg = oxocharcoal.none})
vim.api.nvim_set_hl(0, "NvimTreeEmptyFolderName", {fg = oxocharcoal.lightblue, bg = oxocharcoal.none})
vim.api.nvim_set_hl(0, "NvimTreeOpenedFolderName", {fg = oxocharcoal.lightblue, bg = oxocharcoal.none})
vim.api.nvim_set_hl(0, "NvimTreeNormal", {fg = oxocharcoal.grey04, bg = oxocharcoal.black})
vim.api.nvim_set_hl(0, "NeogitBranch", {fg = oxocharcoal.orange, bg = oxocharcoal.none})
vim.api.nvim_set_hl(0, "NeogitRemote", {fg = oxocharcoal.base09, bg = oxocharcoal.none})
vim.api.nvim_set_hl(0, "NeogitHunkHeader", {fg = oxocharcoal.grey04, bg = oxocharcoal.grey02})
vim.api.nvim_set_hl(0, "NeogitHunkHeaderHighlight", {fg = oxocharcoal.grey04, bg = oxocharcoal.grey03})
vim.api.nvim_set_hl(0, "HydraRed", {fg = oxocharcoal.pink, bg = oxocharcoal.none})
vim.api.nvim_set_hl(0, "HydraBlue", {fg = oxocharcoal.base09, bg = oxocharcoal.none})
vim.api.nvim_set_hl(0, "HydraAmaranth", {fg = oxocharcoal.fushia, bg = oxocharcoal.none})
vim.api.nvim_set_hl(0, "HydraTeal", {fg = oxocharcoal.teal, bg = oxocharcoal.none})
vim.api.nvim_set_hl(0, "HydraHint", {fg = oxocharcoal.none, bg = oxocharcoal.blend})
vim.api.nvim_set_hl(0, "alpha1", {fg = oxocharcoal.grey03, bg = oxocharcoal.none})
vim.api.nvim_set_hl(0, "alpha2", {fg = oxocharcoal.grey04, bg = oxocharcoal.none})
vim.api.nvim_set_hl(0, "alpha3", {fg = oxocharcoal.grey03, bg = oxocharcoal.none})
vim.api.nvim_set_hl(0, "CodeBlock", {fg = oxocharcoal.none, bg = oxocharcoal.grey01})
vim.api.nvim_set_hl(0, "BufferLineDiagnostic", {fg = oxocharcoal.fushia, bg = oxocharcoal.none, bold = true})
vim.api.nvim_set_hl(0, "BufferLineDiagnosticVisible", {fg = oxocharcoal.fushia, bg = oxocharcoal.none, bold = true})
vim.api.nvim_set_hl(0, "htmlH1", {link = "markdownH1"})
vim.api.nvim_set_hl(0, "mkdRule", {link = "markdownRule"})
vim.api.nvim_set_hl(0, "mkdListItem", {link = "markdownListMarker"})
vim.api.nvim_set_hl(0, "mkdListItemCheckbox", {link = "markdownListMarker"})
vim.api.nvim_set_hl(0, "VimwikiHeader1", {link = "markdownH1"})
vim.api.nvim_set_hl(0, "VimwikiHeader2", {link = "markdownH1"})
vim.api.nvim_set_hl(0, "VimwikiHeader3", {link = "markdownH1"})
vim.api.nvim_set_hl(0, "VimwikiHeader4", {link = "markdownH1"})
vim.api.nvim_set_hl(0, "VimwikiHeader5", {link = "markdownH1"})
vim.api.nvim_set_hl(0, "VimwikiHeader6", {link = "markdownH1"})
vim.api.nvim_set_hl(0, "VimwikiHeaderChar", {link = "markdownH1"})
vim.api.nvim_set_hl(0, "VimwikiList", {link = "markdownListMarker"})
vim.api.nvim_set_hl(0, "VimwikiLink", {link = "markdownUrl"})
vim.api.nvim_set_hl(0, "VimwikiCode", {link = "markdownCode"})
vim.api.nvim_set_hl(0, "WhichKey", {link = "method"})
vim.api.nvim_set_hl(0, "WhichKeyGroup", {link = "keyword"})
vim.api.nvim_set_hl(0, "WhichKeyDesc", {link = "text"})
vim.api.nvim_set_hl(0, "WhichKeyValue", {link = "comment"})
return {oxocharcoal = oxocharcoal}